org.gradle.warning.mode=all
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.jvmargs=--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

# Dependency versions
errorproneVersion=2.38.0
errorpronePluginVersion=4.2.0
ideaExtPluginVersion=1.1.10
googleAutoServiceVersion=1.1.1
googleJavaFormatVersion=1.27.0
jspecifyVersion=1.0.0
junitJupiterVersion=5.13.1
liquibaseGroovyDslVersion=4.0.1
liquibasePluginVersion=3.0.2
liquibaseVersion=4.32.0
lombokVersion=1.18.38
mapstructVersion=1.6.3
nullawayVersion=0.12.7
opentelemetryJavaagentVersion=2.16.0
opentelemetrySdkVersion=1.51.0
picocliVersion=4.7.7
spotlessVersion=7.0.4
springBootVersion=3.5.0
springCloudVersion=2025.0.0
springDependencyManagementVersion=1.1.7
springDocOpenApiStarterVersion=2.8.9
