services:
  config:
    container_name: cloud
    hostname: config-service
    build:
      context: ../../..
      dockerfile: docker/cloud/compound/Dockerfile
    environment:
      PROFILE: "container, noconfig"
      OTEL_PROFILE: 'disabled'
    ports:
      - '8761:8761' # discovery-service
      - '8888:8888' # config-service
      - '8080:8080' # gateway-service
    volumes:
      - ../../../config:/root/config
    networks:
      - template-network
