services:
  # Composite cloud service
  discovery-service:
    image: template/composite-cloud
    container_name: composite-cloud
    hostname: config-service
    build:
      context: ../../..
      dockerfile: docker/cloud/composite/Dockerfile
    ports:
      - '8888:8888' # config-service
      - '8761:8761' # discovery-service
      - '8080:8080' # gateway-service
    volumes:
      - ../../../config:/root/config
      - composite-cloud-logs:/app/logs

    networks:
      - template-network

volumes:
  composite-cloud-logs:
