/**
 * Native compilation support.
 */

//file:noinspection GrUnresolvedAccess
apply plugin: 'org.graalvm.buildtools.native'

dependencies {
    // ClassGraph
    implementation "io.github.classgraph:classgraph:${classGraphVersion}"
}

tasks.withType(JavaCompile).matching {
    it.name in ['compileAotJava', 'compileAotTestJava']
}.configureEach {
    options.compilerArgs = options.compilerArgs.findAll { it != '-Werror' && !it.startsWith('-Xlint') }
}

graalvmNative {
    testSupport = false
    binaries {
        named("main") {
            resources.autodetect()
        }
    }
}
