#!/bin/sh
set -e

changedFiles="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" { print $NF}')"

./gradlew spotlessApply

for sourceFilePath in $changedFiles
do
  git add "$sourceFilePath"
done;
