services:
  # Config service
  config-service:
    image: template/config-service
    container_name: config-service
    build:
      context: ../..
      dockerfile: docker/services/Dockerfile
      args:
        APP_DIR: cloud/config-service
    environment:
      SERVER_PORT: 8888
      SPRING_PROFILES_ACTIVE: "container, no-config"
    ports:
      - '8888:8888'
    volumes:
      - ../../config:/root/config
    networks:
      - template-network

  # Discovery service
  discovery-service:
    image: template/discovery-service
    container_name: discovery-service
    build:
      context: ../..
      dockerfile: docker/services/Dockerfile
      args:
        APP_DIR: cloud/discovery-service
    environment:
      SERVER_PORT: 8761
    ports:
      - '8761:8761'
    networks:
      - template-network
    depends_on:
      config-service:
        condition: service_healthy

  # Gateway service
  gateway-service:
    image: template/gateway-service
    container_name: gateway-service
    build:
      context: ../..
      dockerfile: docker/services/Dockerfile
      args:
        APP_DIR: cloud/gateway-service
    networks:
      - template-network
    depends_on:
      discovery-service:
        condition: service_healthy
