apply from: "${rootDir}/tools/gradle/lib/base.gradle"

version = '0.0.1-SNAPSHOT'

dependencies {
    // Spring Boot
    compileOnly 'org.springframework.boot:spring-boot-starter-data-jpa'
    compileOnly 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    compileOnly 'org.springframework.boot:spring-boot-starter-validation'
    compileOnly 'org.springframework.boot:spring-boot-starter-webflux'

    // Spring
//    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    // OpenTelemetry
    compileOnly 'io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi'

    // Google AutoService
    annotationProcessor "com.google.auto.service:auto-service:${googleAutoServiceVersion}"
}
