server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/users
    username: user
    password: password

#  jpa:
#    properties:
#      hibernate:
#        format_sql: true

auth:
  jwt:
    access-token:
      ttl: 43200

    refresh-token:
      secret: refreshSecret
      ttl: 86400

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE
