name: template
include:
  - mysql/compose.yaml
  - broker/kafka.yaml
  - observability/lgtm.yaml
  - cloud/composite/compose.yaml # use composite cloud services
#  - cloud/compose.yaml
  - services/compose.yaml

networks:
  template-network:
