auth:
  jwt:
    access-token:
      secret: your-access-secret

otel:
  exporter:
    otlp:
      endpoint: http://opentelemetry-collector:4317

services:
#  discovery: http://discovery-service:8761
  discovery: http://config-service:8761 # composite cloud
  user: lb://user-service
  weather: lb://weather-service
