spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/root/config

logging:
  level:
    org:
      springframework:
        cloud:
          config:
            server:
              environment: warn
