ext {
    dbUrl = 'jdbc:mysql://127.0.0.1:3306/users'
}

apply from: "${rootDir}/tools/gradle/service/base.gradle"
apply from: "${rootDir}/tools/gradle/service/servlet.gradle"
apply from: "${rootDir}/tools/gradle/service/mysql.gradle"
apply from: "${rootDir}/tools/gradle/service/kafka.gradle"

version = '0.0.1-SNAPSHOT'

dependencies {
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    // Project dependencies
    implementation project(':users-client')
}
