services:
  observability:
    container_name: lgtm
    hostname: opentelemetry-collector
    image: grafana/otel-lgtm:latest
    ports:
      - '4317:4317' # OTLP gRPC
      - '4318:4318' # OTLP HTTP
      - '3000:3000' # Grafana
    networks:
      - template-network
