services:
  mysqldb:
    container_name: mysqldb
    image: mysql:9.3.0
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - template-network

volumes:
  mysql:
