services:
  mysqldb:
    container_name: mysqldb
    image: mysql:9.0.1
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysqldb:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - template-network
