services:
  # User service
  user-service:
    image: template/user-service
    container_name: user-service
    build:
      context: ../..
      dockerfile: docker/services/Dockerfile
      args:
        APP_DIR: services/user/service
    ports:
      - '8081:8080'
    networks:
      - template-network
    depends_on:
      broker:
        condition: service_started
      mysql:
        condition: service_started
      discovery-service:
        condition: service_healthy
      observability:
        condition: service_started

  # Weather service
  weather-service:
    image: template/weather-service
    container_name: weather-service
    build:
      context: ../..
      dockerfile: docker/services/Dockerfile
      args:
        APP_DIR: services/weather/service
    ports:
      - '8082:8080'
    networks:
      - template-network
    depends_on:
      discovery-service:
        condition: service_healthy
      observability:
        condition: service_started
